[book]
authors = ["m1sk9"]
language = "ja"
multilingual = false
src = "src"
title = "ichiyoAI Documentation"

[rust]
edition = "2021"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/approvers/ichiyoAI"
edit-url-template = "https://github.com/approvers/ichiyoAI/edit/main/docs/{path}"
cname = "ichiyoai.approvers.dev"
