name: clippy

on:
  push:
    branches:
      - main
      - 'release/v*.*.*'
  pull_request:
    branches:
      - main
      - 'release/v*.*.*'

jobs:
  clippy:
    runs-on: ubuntu-latest
    name: clippy ichiyoAI
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - uses: mkroening/rust-toolchain-toml@main

      - name: Setup cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "ichiyo-ai/gh-actions-cache"

      - name: Run clippy
        run: cargo clippy --all-targets --all-features
