name: deploy-docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: deploy ichiyoAI docs
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - uses: mkroening/rust-toolchain-toml@main

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: '0.4.36'

      - name: Build docs
        run: |
          cd docs
          mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/book
